export const DEFAULT_CURRENCY_DECIMALS = 2;

export const LOCALE_CURRENCY_MAP = [
  { code: "en-US", name: "English (United States)", currency: "USD" },
  { code: "en-GB", name: "English (United Kingdom)", currency: "GBP" },
  { code: "en-AU", name: "English (Australia)", currency: "AUD" },
  { code: "en-CA", name: "English (Canada)", currency: "CAD" },
  { code: "en-NZ", name: "English (New Zealand)", currency: "NZD" },
  { code: "en-IE", name: "English (Ireland)", currency: "EUR" },
  { code: "en-ZA", name: "English (South Africa)", currency: "ZAR" },
  { code: "en-SG", name: "English (Singapore)", currency: "SGD" },
  { code: "en-PH", name: "English (Philippines)", currency: "PHP" },
  { code: "en-HK", name: "English (Hong Kong)", currency: "HKD" },

  { code: "de-DE", name: "German (Germany)", currency: "EUR" },
  { code: "de-AT", name: "German (Austria)", currency: "EUR" },
  { code: "de-CH", name: "German (Switzerland)", currency: "CHF" },

  { code: "fr-FR", name: "French (France)", currency: "EUR" },
  { code: "fr-CA", name: "French (Canada)", currency: "CAD" },
  { code: "fr-CH", name: "French (Switzerland)", currency: "CHF" },
  { code: "fr-BE", name: "French (Belgium)", currency: "EUR" },
  { code: "fr-LU", name: "French (Luxembourg)", currency: "EUR" },
  { code: "fr-MA", name: "French (Morocco)", currency: "MAD" },
  { code: "fr-TN", name: "French (Tunisia)", currency: "TND" },
  { code: "fr-SN", name: "French (Senegal)", currency: "XOF" },
  { code: "fr-CI", name: "French (Côte d’Ivoire)", currency: "XOF" },
  { code: "fr-CM", name: "French (Cameroon)", currency: "XAF" },
  { code: "fr-CD", name: "French (DR Congo)", currency: "CDF" },

  { code: "es-ES", name: "Spanish (Spain)", currency: "EUR" },
  { code: "es-MX", name: "Spanish (Mexico)", currency: "MXN" },
  { code: "es-AR", name: "Spanish (Argentina)", currency: "ARS" },
  { code: "es-CL", name: "Spanish (Chile)", currency: "CLP" },
  { code: "es-CO", name: "Spanish (Colombia)", currency: "COP" },
  { code: "es-PE", name: "Spanish (Peru)", currency: "PEN" },
  { code: "es-UY", name: "Spanish (Uruguay)", currency: "UYU" },
  { code: "es-PY", name: "Spanish (Paraguay)", currency: "PYG" },
  { code: "es-BO", name: "Spanish (Bolivia)", currency: "BOB" },
  { code: "es-EC", name: "Spanish (Ecuador)", currency: "USD" },
  { code: "es-VE", name: "Spanish (Venezuela)", currency: "VES" },

  { code: "pt-PT", name: "Portuguese (Portugal)", currency: "EUR" },
  { code: "pt-BR", name: "Portuguese (Brazil)", currency: "BRL" },

  { code: "it-IT", name: "Italian (Italy)", currency: "EUR" },
  { code: "nl-NL", name: "Dutch (Netherlands)", currency: "EUR" },
  { code: "nl-BE", name: "Dutch (Belgium)", currency: "EUR" },

  { code: "ru-RU", name: "Russian (Russia)", currency: "RUB" },
  { code: "uk-UA", name: "Ukrainian (Ukraine)", currency: "UAH" },
  { code: "pl-PL", name: "Polish (Poland)", currency: "PLN" },
  { code: "cs-CZ", name: "Czech (Czechia)", currency: "CZK" },
  { code: "sk-SK", name: "Slovak (Slovakia)", currency: "EUR" },
  { code: "hu-HU", name: "Hungarian (Hungary)", currency: "HUF" },
  { code: "ro-RO", name: "Romanian (Romania)", currency: "RON" },
  { code: "bg-BG", name: "Bulgarian (Bulgaria)", currency: "BGN" },
  { code: "sr-RS", name: "Serbian (Serbia)", currency: "RSD" },
  { code: "hr-HR", name: "Croatian (Croatia)", currency: "EUR" },
  { code: "sl-SI", name: "Slovenian (Slovenia)", currency: "EUR" },
  { code: "lt-LT", name: "Lithuanian (Lithuania)", currency: "EUR" },
  { code: "lv-LV", name: "Latvian (Latvia)", currency: "EUR" },
  { code: "et-EE", name: "Estonian (Estonia)", currency: "EUR" },
  { code: "el-GR", name: "Greek (Greece)", currency: "EUR" },
  { code: "mt-MT", name: "Maltese (Malta)", currency: "EUR" },
  { code: "da-DK", name: "Danish (Denmark)", currency: "DKK" },
  { code: "nb-NO", name: "Norwegian Bokmål (Norway)", currency: "NOK" },
  { code: "nn-NO", name: "Norwegian Nynorsk (Norway)", currency: "NOK" },
  { code: "sv-SE", name: "Swedish (Sweden)", currency: "SEK" },
  { code: "fi-FI", name: "Finnish (Finland)", currency: "EUR" },
  { code: "is-IS", name: "Icelandic (Iceland)", currency: "ISK" },

  { code: "zh-CN", name: "Chinese (Simplified, China)", currency: "CNY" },
  { code: "zh-TW", name: "Chinese (Traditional, Taiwan)", currency: "TWD" },
  { code: "zh-HK", name: "Chinese (Traditional, Hong Kong)", currency: "HKD" },
  { code: "zh-SG", name: "Chinese (Simplified, Singapore)", currency: "SGD" },

  { code: "ja-JP", name: "Japanese (Japan)", currency: "JPY" },
  { code: "ko-KR", name: "Korean (South Korea)", currency: "KRW" },

  { code: "hi-IN", name: "Hindi (India)", currency: "INR" },
  { code: "bn-BD", name: "Bengali (Bangladesh)", currency: "BDT" },
  { code: "ne-NP", name: "Nepali (Nepal)", currency: "NPR" },
  { code: "ur-PK", name: "Urdu (Pakistan)", currency: "PKR" },
  { code: "si-LK", name: "Sinhala (Sri Lanka)", currency: "LKR" },
  { code: "ta-LK", name: "Tamil (Sri Lanka)", currency: "LKR" },
  { code: "en-LK", name: "English (Sri Lanka)", currency: "LKR" },
  { code: "ta-IN", name: "Tamil (India)", currency: "INR" },

  { code: "id-ID", name: "Indonesian (Indonesia)", currency: "IDR" },
  { code: "ms-MY", name: "Malay (Malaysia)", currency: "MYR" },
  { code: "ms-SG", name: "Malay (Singapore)", currency: "SGD" },
  { code: "vi-VN", name: "Vietnamese (Vietnam)", currency: "VND" },
  { code: "th-TH", name: "Thai (Thailand)", currency: "THB" },
  { code: "km-KH", name: "Khmer (Cambodia)", currency: "KHR" },
  { code: "lo-LA", name: "Lao (Laos)", currency: "LAK" },
  { code: "my-MM", name: "Burmese (Myanmar)", currency: "MMK" },
  { code: "mn-MN", name: "Mongolian (Mongolia)", currency: "MNT" },

  { code: "ar-SA", name: "Arabic (Saudi Arabia)", currency: "SAR" },
  { code: "ar-AE", name: "Arabic (United Arab Emirates)", currency: "AED" },
  { code: "ar-QA", name: "Arabic (Qatar)", currency: "QAR" },
  { code: "ar-OM", name: "Arabic (Oman)", currency: "OMR" },
  { code: "ar-KW", name: "Arabic (Kuwait)", currency: "KWD" },
  { code: "ar-BH", name: "Arabic (Bahrain)", currency: "BHD" },
  { code: "ar-JO", name: "Arabic (Jordan)", currency: "JOD" },
  { code: "ar-LB", name: "Arabic (Lebanon)", currency: "LBP" },
  { code: "ar-EG", name: "Arabic (Egypt)", currency: "EGP" },
  { code: "ar-MA", name: "Arabic (Morocco)", currency: "MAD" },
  { code: "ar-TN", name: "Arabic (Tunisia)", currency: "TND" },
  { code: "ar-DZ", name: "Arabic (Algeria)", currency: "DZD" },
  { code: "he-IL", name: "Hebrew (Israel)", currency: "ILS" },
  { code: "fa-IR", name: "Persian (Iran)", currency: "IRR" },
  { code: "tr-TR", name: "Turkish (Turkey)", currency: "TRY" },
  { code: "az-AZ", name: "Azerbaijani (Azerbaijan)", currency: "AZN" },
  { code: "ka-GE", name: "Georgian (Georgia)", currency: "GEL" },
  { code: "hy-AM", name: "Armenian (Armenia)", currency: "AMD" },
  { code: "kk-KZ", name: "Kazakh (Kazakhstan)", currency: "KZT" },
  { code: "uz-UZ", name: "Uzbek (Uzbekistan)", currency: "UZS" },
  { code: "tk-TM", name: "Turkmen (Turkmenistan)", currency: "TMT" },

  { code: "af-ZA", name: "Afrikaans (South Africa)", currency: "ZAR" },
  { code: "sw-KE", name: "Swahili (Kenya)", currency: "KES" },
  { code: "sw-TZ", name: "Swahili (Tanzania)", currency: "TZS" },
  { code: "am-ET", name: "Amharic (Ethiopia)", currency: "ETB" },
  { code: "en-NG", name: "English (Nigeria)", currency: "NGN" },
  { code: "en-GH", name: "English (Ghana)", currency: "GHS" },
  { code: "en-KE", name: "English (Kenya)", currency: "KES" },
  { code: "en-UG", name: "English (Uganda)", currency: "UGX" },
  { code: "en-RW", name: "English (Rwanda)", currency: "RWF" },
];
