name: Run unit tests on pull requests
on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project and prepare
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - name: Activate pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Run tests
        run: pnpm run test
